### ISSUE TITLE
polymer-2 branch error

### ISSUE THREAD

**Issue by robertheessels** [tur-nr/polymer-redux#52]
Hi!

I'm trying to get the polymer-2 branch to work with the polymer 2.0 preview.
The behaviour does not seems to work:

this.getState is not a function
this.dispatch is not a function

Seems like the methods are not added to the component.

With the same code, all is fine if I run the normal branch and normal polymer.

**Comment by robertheessels** [comment]
My mistake. It works fine.

**Comment by tur-nr** [comment]
No worries, just be wary with this branch. It's subject to, and probably
will, change.
